-- =====================================================
-- TENDER AI PLATFORM - DATABASE SCHEMA V1
-- Moroccan Government Tenders (marchespublics.gov.ma)
-- =====================================================

-- Enum for tender types
CREATE TYPE tender_type AS ENUM ('AOON', 'AOOI');

-- Enum for tender status
CREATE TYPE tender_status AS ENUM ('SCRAPED', 'LISTED', 'ANALYZED', 'ERROR');

-- Enum for document type classification
CREATE TYPE document_type AS ENUM ('AVIS', 'RC', 'CPS', 'ANNEXE', 'OTHER');

-- Main tenders table
CREATE TABLE public.tenders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Scraping metadata
  reference_url TEXT NOT NULL UNIQUE,
  scraped_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  scrape_date DATE NOT NULL,
  
  -- Status tracking
  status tender_status NOT NULL DEFAULT 'SCRAPED',
  error_message TEXT,
  
  -- Avis metadata (extracted by AI)
  reference_tender TEXT,
  tender_type tender_type,
  issuing_institution TEXT,
  subject TEXT,
  total_estimated_value DECIMAL(15, 2),
  
  -- Submission deadline
  submission_deadline_date DATE,
  submission_deadline_time TIME,
  deadline_source TEXT, -- 'AVIS' | 'RC' | 'ANNEXE' | 'WEBSITE'
  deadline_source_date DATE,
  
  -- Folder opening
  folder_opening_location TEXT,
  
  -- Keywords for search (generated by AI)
  keywords_en TEXT[] DEFAULT '{}',
  keywords_fr TEXT[] DEFAULT '{}',
  keywords_ar TEXT[] DEFAULT '{}',
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Lots table (many-to-one with tenders)
CREATE TABLE public.tender_lots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tender_id UUID NOT NULL REFERENCES public.tenders(id) ON DELETE CASCADE,
  
  lot_number INTEGER NOT NULL,
  lot_subject TEXT,
  lot_estimated_value DECIMAL(15, 2),
  caution_provisoire DECIMAL(15, 2),
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Documents table (stores extracted text)
CREATE TABLE public.tender_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tender_id UUID NOT NULL REFERENCES public.tenders(id) ON DELETE CASCADE,
  
  document_type document_type NOT NULL,
  original_filename TEXT,
  page_count INTEGER,
  
  -- Extracted content
  extracted_text TEXT,
  extraction_method TEXT, -- 'pypdf' | 'paddleocr' | 'docx' | 'xlsx'
  
  -- Provenance tracking
  source_date DATE,
  is_annex_override BOOLEAN DEFAULT false,
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Deep analysis results (triggered on click)
CREATE TABLE public.tender_analysis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tender_id UUID NOT NULL REFERENCES public.tenders(id) ON DELETE CASCADE,
  
  -- Universal fields extracted
  analysis_data JSONB NOT NULL DEFAULT '{}',
  
  -- AI metadata
  model_used TEXT,
  tokens_used INTEGER,
  analysis_cost DECIMAL(10, 6),
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Ask AI chat history
CREATE TABLE public.tender_chats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tender_id UUID NOT NULL REFERENCES public.tenders(id) ON DELETE CASCADE,
  
  user_message TEXT NOT NULL,
  ai_response TEXT,
  
  -- Language detection
  detected_language TEXT, -- 'fr' | 'ar' | 'darija'
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create indexes for performance
CREATE INDEX idx_tenders_status ON public.tenders(status);
CREATE INDEX idx_tenders_scrape_date ON public.tenders(scrape_date DESC);
CREATE INDEX idx_tenders_keywords_en ON public.tenders USING GIN(keywords_en);
CREATE INDEX idx_tenders_keywords_fr ON public.tenders USING GIN(keywords_fr);
CREATE INDEX idx_tenders_keywords_ar ON public.tenders USING GIN(keywords_ar);
CREATE INDEX idx_tender_lots_tender_id ON public.tender_lots(tender_id);
CREATE INDEX idx_tender_documents_tender_id ON public.tender_documents(tender_id);
CREATE INDEX idx_tender_analysis_tender_id ON public.tender_analysis(tender_id);
CREATE INDEX idx_tender_chats_tender_id ON public.tender_chats(tender_id);

-- Enable RLS (public read for now, will add auth later)
ALTER TABLE public.tenders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tender_lots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tender_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tender_analysis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tender_chats ENABLE ROW LEVEL SECURITY;

-- Public read policies (no auth required for V1)
CREATE POLICY "Public read access for tenders"
  ON public.tenders FOR SELECT
  USING (true);

CREATE POLICY "Public read access for tender_lots"
  ON public.tender_lots FOR SELECT
  USING (true);

CREATE POLICY "Public read access for tender_documents"
  ON public.tender_documents FOR SELECT
  USING (true);

CREATE POLICY "Public read access for tender_analysis"
  ON public.tender_analysis FOR SELECT
  USING (true);

CREATE POLICY "Public read access for tender_chats"
  ON public.tender_chats FOR SELECT
  USING (true);

-- Insert/Update/Delete policies for backend API (service role)
CREATE POLICY "Service role full access tenders"
  ON public.tenders FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role full access tender_lots"
  ON public.tender_lots FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role full access tender_documents"
  ON public.tender_documents FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role full access tender_analysis"
  ON public.tender_analysis FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role full access tender_chats"
  ON public.tender_chats FOR ALL
  USING (true)
  WITH CHECK (true);

-- Function to update timestamps
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for tenders updated_at
CREATE TRIGGER update_tenders_updated_at
  BEFORE UPDATE ON public.tenders
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Full-text search function
CREATE OR REPLACE FUNCTION public.search_tenders(search_query TEXT)
RETURNS SETOF public.tenders AS $$
BEGIN
  RETURN QUERY
  SELECT * FROM public.tenders
  WHERE 
    subject ILIKE '%' || search_query || '%'
    OR issuing_institution ILIKE '%' || search_query || '%'
    OR reference_tender ILIKE '%' || search_query || '%'
    OR search_query = ANY(keywords_en)
    OR search_query = ANY(keywords_fr)
    OR search_query = ANY(keywords_ar)
  ORDER BY scrape_date DESC;
END;
$$ LANGUAGE plpgsql;